### ISSUE TITLE
Trouble Installing On Windows 7 64bit

### ISSUE THREAD

**Issue by AlphonsoFaye** [neuralfirings/BlenderCaddie#7]
Hey, looks like a promising project, but have you tested this on Windows yet? I can't seem to get this to install on Windows 7 64bit, Blender 2.73 or 2.74. 
I think this is the right place to put this, sorry I'm new to GitHub ^^

**Comment by neuralfirings** [comment]
Yes, this is the right place. Sorry for the late response. Hmm, it's working for me. Same system, Windows 7 64 Bit, Blender 2.74. 

Are you using this in Edit Mode? It currently only works in Edit Mode because you have to select edges you want to resize.

**Comment by AlphonsoFaye** [comment]
Ahh, my apologies:  I was installing the .py file when the documentation clearly states to install the .zip!
Working properly for me, will close this issue now.
